### ISSUE TITLE
Sharing of content on twitter [QC-105]

### ISSUE THREAD

**Issue by vidvidvid** [quest-chains/dapp#100]
### Prerequisite

We need to enable binding the twitter handle to the wallet address

## Quest chain
  - [ ] somewhere in the quest chain view
  - [ ] maybe in the explorer
  - [ ] celebratory window/modal after creating the quest chain

“Have you got what it takes? Try to complete this quest chain to obtain it’s soulbound NFT! <link> <NFT image> <@owner twitter handle>”

## NFT #94 
- [ ] after minting
- [ ] in the gallery view (on hover & when the modal opens)

“I have just minted the NFT from <quest chain name> by <@owner twitter handle>.”
    Add the NFT image to the twitter post.
          
## Quests
- [ ] first we’d need to implement the quest view

“some similar message to the quest chain’s message”

**Comment by davort** [comment]
Comment from [Linear (#105)](https://linear.app/quest-chains/issue/QC-105/sharing-of-content-on-twitter-quest-chainsdapp-100)

@dan13ram @weetopol In light of the ongoing shitstorm around Twitter, would it perhaps be wise to add an option to share to Mastodon as well?

---
*via LinearSync*

**Comment by vidvidvid** [comment]
@davort haven't heard of Mastodon yet, but if you suggest to add it, i can do that. I'd also add the button to the quest chain view - something like that:
<img width="804" alt="Screenshot 2022-11-17 at 11 36 11" src="https://user-images.githubusercontent.com/35112939/202424148-fbc1f38e-658a-4c8b-8c57-e478764b5be5.png">
yay/nay?

**Comment by davort** [comment]
> I'd also add the button to the quest chain view - something like that: <img alt="Screenshot 2022-11-17 at 11 36 11" width="804" src="https://user-images.githubusercontent.com/35112939/202424148-fbc1f38e-658a-4c8b-8c57-e478764b5be5.png"> yay/nay?

Can't see the button to the quest chain view in this screenshot 🤔 Wrong screenshot?

**Comment by vidvidvid** [comment]
I mean i would add the tweet button to the quest chain view. Like you add salt to the soup.

**Comment by davort** [comment]
Oh OK, I thought we'd already agreed on that :) Sure thing! I'd suggest a slight modification, to have it separate from the chain data. How about this?
![image](https://user-images.githubusercontent.com/1573304/202430187-1b37f1ba-2b1e-40a8-90d2-741f85bf8945.png)

**Comment by vidvidvid** [comment]
Lovely! :D

**Comment by davort** [comment]
Comment from [Linear (#105)](https://linear.app/quest-chains/issue/QC-105/sharing-of-content-on-twitter-quest-chainsdapp-100)

Here's the link to the Figma file: 

You should be able to extract the Mastodon icon from here.

[👀  \[Date\] - Design review - \[WIP\] Social sharing (Figma)](https://www.figma.com/file/nwXFUJlrYPnESGjZp9AWHt/%5BWIP%5D-Social-sharing?node-id=1%3A6)

---
*via LinearSync*

**Comment by vidvidvid** [comment]
@davort what do you think about adding a celebratory modal along with the share buttons after creating a quest chain?

**Comment by davort** [comment]
Comment from [Linear (#105)](https://linear.app/quest-chains/issue/QC-105/sharing-of-content-on-twitter-quest-chainsdapp-100)

Sure thing @weetopol - I might even have a design for it half-made already 😃 Opened a separate sub-issue for that: [QC-112](https://linear.app/quest-chains/issue/QC-112/nft-modal-enhancements) 

---
*via LinearSync*

**Comment by vidvidvid** [comment]
nice! :)

**Comment by davort** [comment]
Comment from [Linear (#105)](https://linear.app/quest-chains/issue/QC-105/sharing-of-content-on-twitter-quest-chainsdapp-100)

I took the design from [QC-113](https://linear.app/quest-chains/issue/QC-113/celebratory-modal-upon-creating-a-quest-chain) and applied it after minting. Would you change anything?

![Screenshot 2022-11-19 at 21.59.07.png](https://uploads.linear.app/f8a9257c-3476-46b9-9ff4-3030b70ec931/bce7082e-18bb-4242-bacb-1fd73d9d9482/bbdfaebd-6d1d-47e9-b48b-a8f44eefb768)

---
*via LinearSync*

**Comment by davort** [comment]
Comment from [Linear (#105)](https://linear.app/quest-chains/issue/QC-105/sharing-of-content-on-twitter-quest-chainsdapp-100)

I presume the version with the NFT would be preferable here, too?

How about this? 

I left some notes in this Figma page, hope they will be helpful.

[NFT minted - \[WIP\] Social sharing (Figma)](https://www.figma.com/file/nwXFUJlrYPnESGjZp9AWHt/%5BWIP%5D-Social-sharing?node-id=127%3A5812&t=Am1MQHVMyeMC76bu-4)

---
*via LinearSync*

**Comment by vidvidvid** [comment]
looks great, i'll add it!
