### ISSUE TITLE
Enhance chain edit mode [QC-118]

### ISSUE THREAD

**Issue by davort** [quest-chains/dapp#113]
Arrange the edit mode layout in a way that makes it obvious how things work. Make sure to account for all editable sections: title, description, members. Referrence: [https://discord.com/channels/991666831196696627/991669245018656808/1044603711890128956](https://discord.com/channels/991666831196696627/991669245018656808/1044603711890128956)

___

Automatically created from [Linear (#118)]()

*via LinearSync*

**Comment by vidvidvid** [comment]
done in the recent PR by dan
