### ISSUE TITLE
Create a global footer [QC-127]

### ISSUE THREAD

**Issue by davort** [quest-chains/dapp#122]
It should be at the bottom of every page, both on the Landing page and in the App.

___

Automatically created from [Linear (#127)]()

*via LinearSync*

**Comment by vidvidvid** [comment]
![Screenshot 2022-12-19 at 12 59 17](https://user-images.githubusercontent.com/35112939/208421252-aaf8d85b-83a8-471b-8fdc-699f7be50964.png)
