### ISSUE TITLE
Make it clear that the user is one of the members of the chain [QC-134]

### ISSUE THREAD

**Issue by davort** [quest-chains/dapp#129]
When the user sees a list of members for the chain, make it clear if one of the members is them. This could be achieved by simple addition of the "(You)" suffix after the wallet address that belongs to them. Feel free to look into other possible solutions.

___

Automatically created from [Linear (#134)]()

*via LinearSync*

**Comment by vidvidvid** [comment]
@davort is that fine or would you like to add some of the address?

![Screenshot 2022-12-19 at 12 58 06](https://user-images.githubusercontent.com/35112939/208421027-87135f2f-9496-4c9a-8b8a-5021b692a4ac.png)
![Screenshot 2022-12-19 at 12 57 59](https://user-images.githubusercontent.com/35112939/208421034-4032e0f8-37b3-4280-9832-0cce205b9d72.png)

**Comment by dan13ram** [comment]
closing this as its already implemented
