### ISSUE TITLE
Fix Consistent NextJS Hydration Errors [QC-167]

### ISSUE THREAD

**Issue by dan13ram** [quest-chains/dapp#162]

**Comment by parv3213** [comment]
@dan13ram I do not see this issue with the latest dev build, c9567839cce465d221313884603d1fb7d84789d5.

**Comment by dan13ram** [comment]
@parv3213 I still saw them. I pushed a fix in [a1efc21](https://github.com/quest-chains/dapp/pull/175/commits/a1efc21087346b5477fa0938af5333d6584c34f6) 
can you check if looks good on your side. its the branch `feat/profile`

**Comment by parv3213** [comment]
<img width="360" alt="Screenshot 2023-02-14 at 11 54 31 AM" src="https://user-images.githubusercontent.com/45873074/218656265-8f8d89e4-05d9-48ab-ac95-5caccab9db67.png">
I do not see any hydration issues. Although I am asked to sign this message and after signing, nothing happens. Hence I am unable to connect my wallet.

**Comment by parv3213** [comment]
Oh I guess because I need to add MONGODB_URI?
