### ISSUE TITLE
Fix percentage display of progress in profile

### ISSUE THREAD

**Issue by vidvidvid** [quest-chains/dapp#42]
<img width="634" alt="Screenshot 2022-09-26 at 16 29 07" src="https://user-images.githubusercontent.com/35112939/192303574-8856393b-2b5e-42d8-8843-77e8e5b19dd2.png">

**Comment by vidvidvid** [comment]
@adarshajit lovely! :) make sure to open a PR to the `dev` branch.

**Comment by vidvidvid** [comment]
@adarshajit oh yes, need to update our readme :)
please use this:
```
  NEXT_PUBLIC_SUPPORTED_NETWORKS=0x89 0x64 0x5 0x13881
  NEXT_PUBLIC_INFURA_ID=<your_id>
  NEXT_PUBLIC_API_URL=https://api.questchains.xyz
```

**Comment by dan13ram** [comment]
@adarshajit I've pushed a commit to `dev` with the right sample env.
Its in the root folder, so a simple `cp sample.env .env` should work

**Comment by vidvidvid** [comment]
@adarshajit we don't support it brave wallet yet. could you try metamask?

**Comment by dan13ram** [comment]
@adarshajit are you on our discord, would be much easier to have these conversations over there. 

Brave wallet "should" work, are you sure you are on the right network?

**Comment by vidvidvid** [comment]
i just know that last time dysbulic wanted to use the app by being logged in with brave wallet he also had problems :/

**Comment by dan13ram** [comment]
@vidvidvid was this ever fixed ?

**Comment by vidvidvid** [comment]
@dan13ram yeah, i think it was by @adarshajit

**Comment by dan13ram** [comment]
cool, I'm closing this
