### ISSUE TITLE
Prompt to share a newly minted NFT [QC-99]

### ISSUE THREAD

**Issue by davort** [quest-chains/dapp#94]
When the NFT is minted, prompt to share it!!! Tag @questchainz on the tweet - free marketing (feedback from Urbanika)

___

Automatically created from [Linear (#99)]()

*via LinearSync*

**Comment by vidvidvid** [comment]
101.xyz's approach: 
<img width="448" alt="Screenshot 2022-11-05 at 17 51 37" src="https://user-images.githubusercontent.com/35112939/200131850-d556d52e-4c7a-43fc-9a60-71d0432897b0.png">

**Comment by dan13ram** [comment]
We can also add links to opensea (on polygon) and eporio (on gnosis chain) for the NFTs

**Comment by dan13ram** [comment]
Closing as this is completed.
